apiVersion: v1
kind: ConfigMap
metadata:
  name: workhub-config
  namespace: workhub-prod
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "workhub"
  RABBITMQ_HOST: "rabbitmq-service"
  JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseG1GC"
